kind: Pod
apiVersion: v1
metadata:
  name: azure-kv-pod
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: cont
    image: aramase/azure-keyvault:v0.1
    imagePullPolicy: Always
    args:
    - --keyvault-name=kubecon-eu-2021
    - --keyvault-secret-name=app-secret
    env:
    - name: AZURE_CLIENT_ID
      valueFrom:
        secretKeyRef:
          key: clientid
          name: secrets-store-creds
    - name: AZURE_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          key: clientsecret
          name: secrets-store-creds
    - name: AZURE_TENANT_ID
      valueFrom:
        secretKeyRef:
          key: tenantid
          name: secrets-store-creds
