
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: csi-spc
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"                 # [OPTIONAL] if not provided, will default to "false"
    keyvaultName: "kubecon-eu-2021"         # the name of the Keyvault
    objects: |
      array:
        - |
          objectName: app-secret
          objectType: secret                                            # object types: secret, key or cert
          objectVersion: ""                                             # [OPTIONAL] object versions, default to latest if empty
    tenantId: "<tenant id>"                   # the tenant ID of the KeyVault
