apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: csi-spc
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: projects/csi-secret-demo-kubecon2021/secrets/app-secret/versions/latest
        fileName: app-secret
