kind: Pod
apiVersion: v1
metadata:
  name: gcp-secret-manager-pod
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: cont
    image: aramase/google-secret-manager:v0.1
    imagePullPolicy: Always
    args:
    - --secret-name=projects/csi-secret-demo-kubecon2021/secrets/app-secret/versions/latest
    volumeMounts:
      - name: gcp-key
        mountPath: /var/secrets/google
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /var/secrets/google/key.json
  volumes:
    - name: gcp-key
      secret:
        secretName: secrets-store-creds
